---
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This repo details how to run the spatially-explicit projection model submitted for review by Petracca et al.

The "scripts" section has three codes (described in a_DESCRIPTION.txt) -- one to run the IPM for the data collection period (2009-2020) and two different versions of the projection model for the years 2020-2070. The latter scripts differ based on chosen territory selection method.

This code also has four scripts in the "Preliminary_Analysis_Steps" folder for processing of GPS collar data for the territory size and RSF analyses. However, these data are not available publicly due to their sensitive nature. Interested parties should contact Donny Martorello at WDFW (Donny.Martorello@dfw.wa.gov).

The "data" section has all data (in .Rdata formatting) needed to run all spatially-explicit projection models. See a_DESCRIPTION.txt for more.

The "function" section has functions related to the individual-based movement model. These functions allow for attraction of lone wolves, lethal removals, and dispersal of wolves depending on chosen territory selection method. See a_DESCRIPTION.txt for more.
